# Generated by Django 4.0.6 on 2022-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=24, unique=True)),
                ('profile_image', models.TextField(default='default_image')),
                ('name', models.CharField(default=None, max_length=10)),
                ('birth', models.TextField(default=None)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
