# Generated by Django 4.0.6 on 2022-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
