# Generated by Django 4.0.6 on 2022-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image_url',
            field=models.ImageField(upload_to='Feed'),
        ),
    ]
