# Generated by Django 4.0.6 on 2022-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_feed_remove_postimage_post_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.TextField(default=''),
        ),
    ]
