# Generated by Django 4.0.6 on 2022-08-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='post',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.TextField(default='default_image.png'),
        ),
    ]
