# Generated by Django 4.0.6 on 2022-08-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_post_feed_user_id_alter_feed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user_id',
            new_name='user',
        ),
    ]
